version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    groups:
      minor-updates:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 1

    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "npm"
    directory: "/back"
    schedule:
      interval: "daily"
    groups:
      minor-updates:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-updates:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
